services:
  lamp:
    build:
      context: ../  # ルートをコンテキストにする
      dockerfile: lamp-mongo/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
